message:
  opened:
    footer: "Hello @{name}, Thank you for everything !"
    header: "Bye bye!"
  updated:
    footer: "Hello @{name}, Thank you for updating man!"
    header: "Bye !"

ignore:
 - W391
 - E203
